import { defineNuxtModule } from '@nuxt/kit'
import {
  AI_ANSWER_AGENTS,
  AI_TRAINING_CRAWLERS,
} from '../shared/ai-agents'

/**
 * Deliberate AI-crawler policy for robots.txt.
 *
 * Left to `@nuxtjs/seo` defaults, robots.txt says nothing about AI crawlers at
 * all — which is itself a policy, just an accidental one. This module writes the
 * split that actually matters:
 *
 * - **Answer engines are always allowed.** `OAI-SearchBot`, `Claude-SearchBot`,
 *   `PerplexityBot` and the user-triggered `*-User` fetchers fetch a page to
 *   answer a question and cite it back. For a validation site, being absent from
 *   AI answers is indistinguishable from not existing. Not configurable — a site
 *   that wants to be invisible to AI answers should set `robots.enabled: false`
 *   and mean it.
 * - **Training crawlers are a per-site choice.** `GPTBot`, `Google-Extended`,
 *   `CCBot` and friends take content into a corpus with no click and no citation
 *   back. Default `'allow'`: presence in the corpus is what makes a model able to
 *   talk about you unprompted, and a pre-product validation site is trying to be
 *   found, not to protect an archive. Sites with content worth withholding flip
 *   one flag.
 *
 * The user-agent lists come from `shared/ai-agents.ts` — the same taxonomy the
 * visitor classifier uses, so robots.txt and the signal stream can't drift apart.
 *
 * ```ts
 * // nuxt.config.ts — consumer site
 * aiRobots: {
 *   training: 'disallow',      // keep this site out of training corpora
 *   disallow: ['/internal/'],  // hidden from every AI agent, answer engines included
 * }
 * ```
 */
export interface AiRobotsOptions {
  /** Set `false` to emit no AI groups at all and fall back to plain SEO defaults. */
  enabled?: boolean
  /**
   * Stance on training/dataset crawlers.
   * @default 'allow'
   */
  training?: 'allow' | 'disallow'
  /**
   * Paths withheld from every AI agent, answer engines included. Additive to the
   * site-wide `robots.disallow`.
   * @default []
   */
  disallow?: string[]
}

interface RobotsGroup {
  comment: string[]
  userAgent: string[]
  allow?: string[]
  disallow?: string[]
}

/** Build the groups without touching Nuxt — kept pure so it is unit-testable. */
export function buildAiRobotsGroups(options: AiRobotsOptions = {}): RobotsGroup[] {
  const training = options.training ?? 'allow'
  const extraDisallow = options.disallow ?? []

  return [
    {
      comment: [
        'AI answer engines and user-triggered assistant fetches.',
        'Always allowed: these fetches cite back, so blocking them removes this',
        'site from AI answers.',
      ],
      userAgent: [...AI_ANSWER_AGENTS],
      allow: ['/'],
      disallow: extraDisallow,
    },
    {
      comment: [
        `AI training crawlers — policy: ${training} (aiRobots.training).`,
        'These feed a training corpus; there is no click and no citation back.',
      ],
      userAgent: [...AI_TRAINING_CRAWLERS],
      ...(training === 'allow'
        ? { allow: ['/'], disallow: extraDisallow }
        : { disallow: ['/'] }),
    },
  ]
}

export default defineNuxtModule<AiRobotsOptions>({
  meta: {
    name: 'ai-robots',
    configKey: 'aiRobots',
    compatibility: {
      nuxt: '>=3.0.0',
    },
  },

  defaults: {
    enabled: true,
    training: 'allow',
    disallow: [],
  },

  setup(options, nuxt) {
    if (options.enabled === false) return

    // `nuxt.options.robots` is typed by `@nuxtjs/robots` only once its module
    // types are generated, which hasn't happened yet during layer setup — same
    // reason `modules/config.ts` reaches for `nuxt.options` untyped for `llms`.
    const opts = nuxt.options as unknown as Record<string, unknown>
    const robots = (opts.robots ?? {}) as { groups?: unknown[] }

    robots.groups = [...(robots.groups ?? []), ...buildAiRobotsGroups(options)]
    opts.robots = robots
  },
})

// `NuxtConfig['aiRobots']` is generated by Nuxt from `configKey` + this module's
// options type — no manual `nuxt/schema` augmentation (adding one collides with
// the generated declaration's modifiers).
