business:
  name: Incubrain
  legalName: Incubrain Pvt. Ltd.
  foundingYear: 2023
  logo: /favicon-96x96.png
  mission: Empowering technical solopreneurs to leverage AI, compute, and mentorship to outperform traditional 20+ person teams.
socials:
  x: https://x.com/DrewMacGibbon
  youtube: https://www.youtube.com/@DrewMacGibbon
  github: https://github.com/incubrain
